In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Project locations
PROJECT_DIR = Path.home() / "Documents" / "Chip-Product-Analysis"
DATA_DIR = PROJECT_DIR / "data"
NOTEBOOK_DIR = PROJECT_DIR / "notebooks"

print("Project folder:", PROJECT_DIR)
print("Project folder exists:", PROJECT_DIR.exists())
print("Data folder exists:", DATA_DIR.exists())
print("CSV files found:", list(DATA_DIR.glob("*.csv")))

Matplotlib is building the font cache; this may take a moment.

Project folder: C:\Users\udits\Documents\Chip-Product-Analysis
Project folder exists: True
Data folder exists: True
CSV files found: [WindowsPath('C:/Users/udits/Documents/Chip-Product-Analysis/data/museum-fields-2026-10-04.csv')]

In [2]:
CSV_PATH = DATA_DIR / "museum-fields-2026-10-04.csv"

if not CSV_PATH.exists():
    print("CSV not found. Check the file location and filename.")
else:
    df = pd.read_csv(CSV_PATH, low_memory=False)

    print("Dataset loaded successfully!")
    print("Rows:", df.shape[0])
    print("Columns:", df.shape[1])

    display(df.head())

Dataset loaded successfully!
Rows: 281415
Columns: 26

,Object ID,Object name,Entity kind,Company,Specification,Value,Unit,State,Confidence,Source ID,...,Source license,Source license URL,Supporting sources,Alternatives,Conditions,Baseline,Note,Source-reported value,Source-reported unit,Unit conversion
0,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,Record year,2019,NaN,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,Year basis: launched. This is distinct from so...,2019,NaN,NaN
1,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,Enabled CPU cores,6,cores,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,6,cores,NaN
2,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,Threads,12,threads,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,12,threads,NaN
3,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,CPU-core process,TSMC 7nm FinFET,NaN,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,TSMC 7nm FinFET,NaN,NaN
4,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,L3 cache,32,MB,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,32,MB,NaN

In [3]:
# Column names
print("Column names:")
print(df.columns.tolist())

# Data types
print("\nData types:")
display(df.dtypes.rename("Data Type").to_frame())

# Missing values
missing_summary = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percent": (df.isna().mean() * 100).round(2)
}).sort_values("Missing_Percent", ascending=False)

display(missing_summary.head(15))

# First few records
display(df.head(10))

Column names:
['Object ID', 'Object name', 'Entity kind', 'Company', 'Specification', 'Value', 'Unit', 'State', 'Confidence', 'Source ID', 'Source URL', 'Source location', 'Scope', 'Source date', 'Retrieved at', 'Evidence class', 'Source license', 'Source license URL', 'Supporting sources', 'Alternatives', 'Conditions', 'Baseline', 'Note', 'Source-reported value', 'Source-reported unit', 'Unit conversion']

Data types:

                      Data Type
Object ID                   str
Object name                 str
Entity kind                 str
Company                     str
Specification               str
Value                       str
Unit                        str
State                       str
Confidence                  str
Source ID                   str
Source URL                  str
Source location             str
Scope                       str
Source date                 str
Retrieved at                str
Evidence class              str
Source license              str
Source license URL          str
Supporting sources          str
Alternatives                str
Conditions                  str
Baseline                    str
Note                        str
Source-reported value       str
Source-reported unit        str
Unit conversion             str

                       Missing_Count  Missing_Percent
Baseline                      281410           100.00
Unit conversion               281414           100.00
Conditions                    281374            99.99
Source-reported unit          205531            73.03
Unit                          205531            73.03
Confidence                    179668            63.84
Source date                   179349            63.73
State                         179306            63.72
Source license URL            146458            52.04
Note                          129974            46.19
Source license                   877             0.31
Source-reported value             32             0.01
Value                             32             0.01
Entity kind                        0             0.00
Object ID                          0             0.00

,Object ID,Object name,Entity kind,Company,Specification,Value,Unit,State,Confidence,Source ID,...,Source license,Source license URL,Supporting sources,Alternatives,Conditions,Baseline,Note,Source-reported value,Source-reported unit,Unit conversion
0,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,Record year,2019,NaN,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,Year basis: launched. This is distinct from so...,2019,NaN,NaN
1,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,Enabled CPU cores,6,cores,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,6,cores,NaN
2,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,Threads,12,threads,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,12,threads,NaN
3,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,CPU-core process,TSMC 7nm FinFET,NaN,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,TSMC 7nm FinFET,NaN,NaN
4,amd-ryzen-5-3600,AMD Ryzen 5 3600,sku,AMD,L3 cache,32,MB,NaN,NaN,amd-3600,...,NaN,NaN,[],[],NaN,NaN,NaN,32,MB,NaN
5,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,sku,AMD,Record year,2020,NaN,NaN,NaN,amd-5600x,...,NaN,NaN,[],[],NaN,NaN,Year basis: launched. This is distinct from so...,2020,NaN,NaN
6,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,sku,AMD,Enabled CPU cores,6,cores,NaN,NaN,amd-5600x,...,NaN,NaN,[],[],NaN,NaN,NaN,6,cores,NaN
7,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,sku,AMD,Threads,12,threads,NaN,NaN,amd-5600x,...,NaN,NaN,[],[],NaN,NaN,NaN,12,threads,NaN
8,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,sku,AMD,L3 cache,32,MB,NaN,NaN,amd-5600x,...,NaN,NaN,[],[],NaN,NaN,NaN,32,MB,NaN
9,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,sku,AMD,Default TDP,65,W,NaN,NaN,amd-5600x,...,NaN,NaN,[],[],NaN,NaN,NaN,65,W,NaN

In [6]:
# 1. Count unique products and manufacturers
print("Total specification records:", len(df))
print("Unique objects:", df["Object ID"].nunique())
print("Unique object names:", df["Object name"].nunique())
print("Unique companies:", df["Company"].nunique())
print("Unique specifications:", df["Specification"].nunique())

# 2. Types of objects in the dataset
print("\nEntity types:")
display(df["Entity kind"].value_counts().to_frame("Record_Count"))

# 3. Companies with the most records
print("\nTop 10 companies by specification records:")
display(df["Company"].value_counts().head(10).to_frame("Record_Count"))

# 4. Most frequently recorded specifications
print("\nTop 15 specifications:")
display(df["Specification"].value_counts().head(15).to_frame("Record_Count"))

Total specification records: 281415
Unique objects: 20340
Unique object names: 20318
Unique companies: 225
Unique specifications: 751

Entity types:

                      Record_Count
Entity kind
sku                         198381
board                        46044
product-family               33258
microarchitecture             2489
silicon-design                 585
specimen                       432
equipment                       87
device                          55
document                        26
process                         20
system                          19
person                           4
memory-technology                3
package                          3
packaging-technology             2
process-stage                    2
die                              1
isa                              1
core                             1
material                         1
wafer                            1

Top 10 companies by specification records:

                    Record_Count
Company
Intel                     101394
STMicroelectronics         33469
AMD                        33324
MSI                         8612
ASUS                        7729
Freescale                   6977
Cavium                      6967
Zilog                       6644
Gigabyte                    6075
EVGA                        3462

Top 15 specifications:

                  Record_Count
Specification
Series                   17072
Record scope             15596
Part number              13882
Package type             11874
Listed clock             10627
Cores                     8465
L2 cache                  6388
Base clock                6080
Source chip type          5936
ISA                       5725
Memory type               5471
Boost clock               4931
Host interface            4722
GPU model                 4160
Part numbers              3974

In [4]:
# Check whether entire rows are duplicated
print("Exact duplicate rows:", df.duplicated().sum())

# Check whether important identifying fields are missing
for col in ["Object ID", "Object name", "Entity kind",
            "Company", "Specification", "Value"]:
    print(f"{col}: {df[col].isna().sum()} missing values")

# Inspect the available values and units
print("\nExample specification names:")
display(df["Specification"].drop_duplicates().head(20).to_frame())

print("\nExample units:")
display(df["Unit"].dropna().value_counts().head(20).to_frame("Count"))

Exact duplicate rows: 0
Object ID: 0 missing values
Object name: 0 missing values
Entity kind: 0 missing values
Company: 0 missing values
Specification: 0 missing values
Value: 32 missing values

Example specification names:

            Specification
0             Record year
1       Enabled CPU cores
2                 Threads
3        CPU-core process
4                L3 cache
9             Default TDP
11           CCXs per CCD
12     Maximum L3 per CCX
13               Die area
14         Identification
16                   Year
17                Process
18              GPU cores
19     Reported die width
20    Reported die height
21      Reported die area
22                Foundry
23  Verified die geometry
24                    CPU
25            Ray tracing

Example units:

       Count
Unit
MHz    24432
bytes  10114
KiB     5943
mm      5709
W       5454
GB      4078
bit     3358
MiB     2706
Hz      2085
nm      2066
GHz     1517
GiB     1473
GiB/s   1371
MB      1311
°C      1310
mm²     1058
GT/s     824
V        686
µm       246
bits      28

In [5]:
# Create the reports folder if needed
REPORT_DIR = PROJECT_DIR / "reports"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

# Summarize missing values
quality_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": [str(dtype) for dtype in df.dtypes],
    "Missing_Count": df.isna().sum().values,
    "Missing_Percent": (df.isna().mean().values * 100).round(2)
})

quality_summary.to_csv(
    REPORT_DIR / "data_quality_summary.csv",
    index=False
)

print("Data-quality report saved to:")
print(REPORT_DIR / "data_quality_summary.csv")

Data-quality report saved to:
C:\Users\udits\Documents\Chip-Product-Analysis\reports\data_quality_summary.csv

In [7]:
# Select individual product records only
cpu_products = df[
    (df["Entity kind"] == "sku") &
    (
        df["Object name"].str.contains(
            r"\b(Ryzen|Core i[3579]|Xeon|EPYC|Pentium|Celeron|"
            r"Threadripper|Athlon)\b",
            case=False,
            na=False,
            regex=True
        )
    )
].copy()

print("Potential CPU product specification records:", len(cpu_products))
print("Unique CPU product IDs:", cpu_products["Object ID"].nunique())
print("Manufacturers:", cpu_products["Company"].nunique())

display(
    cpu_products[
        ["Object ID", "Object name", "Company", "Specification", "Value", "Unit"]
    ].head(15)
)

Potential CPU product specification records: 73663
Unique CPU product IDs: 1621
Manufacturers: 2

C:\Users\udits\AppData\Local\Temp\ipykernel_5720\793194712.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df["Object name"].str.contains(

,Object ID,Object name,Company,Specification,Value,Unit
0,amd-ryzen-5-3600,AMD Ryzen 5 3600,AMD,Record year,2019,NaN
1,amd-ryzen-5-3600,AMD Ryzen 5 3600,AMD,Enabled CPU cores,6,cores
2,amd-ryzen-5-3600,AMD Ryzen 5 3600,AMD,Threads,12,threads
3,amd-ryzen-5-3600,AMD Ryzen 5 3600,AMD,CPU-core process,TSMC 7nm FinFET,NaN
4,amd-ryzen-5-3600,AMD Ryzen 5 3600,AMD,L3 cache,32,MB
5,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,AMD,Record year,2020,NaN
6,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,AMD,Enabled CPU cores,6,cores
7,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,AMD,Threads,12,threads
8,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,AMD,L3 cache,32,MB
9,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,AMD,Default TDP,65,W
102,bc-cpu-007a5a23-1e12-45b7-90d0-565b80876539,AMD Ryzen Threadripper 9980X,AMD,Record scope,CPU SKU,NaN
103,bc-cpu-007a5a23-1e12-45b7-90d0-565b80876539,AMD Ryzen Threadripper 9980X,AMD,Part numbers,100-000001593WOF; 100-100001593WOF; AMD Ryzen ...,NaN
104,bc-cpu-007a5a23-1e12-45b7-90d0-565b80876539,AMD Ryzen Threadripper 9980X,AMD,Release year,2025,NaN
105,bc-cpu-007a5a23-1e12-45b7-90d0-565b80876539,AMD Ryzen Threadripper 9980X,AMD,Series,Ryzen Threadripper 9000,NaN
106,bc-cpu-007a5a23-1e12-45b7-90d0-565b80876539,AMD Ryzen Threadripper 9980X,AMD,Architecture,Zen 5,NaN

In [8]:
# Find the most common specifications among selected products
display(
    cpu_products["Specification"]
    .value_counts()
    .head(25)
    .to_frame("Record_Count")
)

                              Record_Count
Specification
Process                               1674
Threads                               1621
Architecture                          1619
Cores                                 1619
L2 cache                              1616
Base clock                            1606
Listed TDP                            1605
Series                                1573
L3 cache                              1570
Maximum memory                        1569
Memory type                           1551
Memory channels                       1403
Part number                           1388
Boost clock                           1338
Foundry                               1252
Model name                            1185
Designer                              1185
Model number                          1185
Market                                1185
Product family                        1185
CPU word size                         1185
Maximum CPU sockets                   1184
L1 instruction cache                  1172
L1 instruction organization           1172
L1 instruction associativity          1172

In [9]:
clock_rows = cpu_products[
    cpu_products["Specification"].str.contains(
        r"clock|frequency",
        case=False,
        na=False
    )
]

display(
    clock_rows[
        ["Object name", "Company", "Specification", "Value", "Unit"]
    ].head(30)
)

print("\nClock units:")
display(clock_rows["Unit"].value_counts(dropna=False).to_frame("Count"))

,Object name,Company,Specification,Value,Unit
111,AMD Ryzen Threadripper 9980X,AMD,Base clock,3.2,GHz
112,AMD Ryzen Threadripper 9980X,AMD,Boost clock,5.4,GHz
130,Intel Xeon E5 1650 V3 OEM/Tray 3.5 GHz 6-Core ...,Intel,Base clock,3.5,GHz
131,Intel Xeon E5 1650 V3 OEM/Tray 3.5 GHz 6-Core ...,Intel,Boost clock,3.8,GHz
146,Intel Xeon E3 1245 V5 OEM/Tray 3.5 GHz 4-Core ...,Intel,Base clock,3.5,GHz
147,Intel Xeon E3 1245 V5 OEM/Tray 3.5 GHz 4-Core ...,Intel,Boost clock,3.9,GHz
163,Intel Xeon E5-2660 v4,Intel,Base clock,2,GHz
164,Intel Xeon E5-2660 v4,Intel,Boost clock,3.2,GHz
219,Intel Core i5 6400T OEM/Tray,Intel,Base clock,2.2,GHz
220,Intel Core i5 6400T OEM/Tray,Intel,Boost clock,2.8,GHz
240,Intel Core i9 13900T OEM/Tray,Intel,Base clock,1.1,GHz
241,Intel Core i9 13900T OEM/Tray,Intel,Boost clock,5.3,GHz
242,Intel Core i9 13900T OEM/Tray,Intel,Efficiency-core Base clock,1.1,GHz
243,Intel Core i9 13900T OEM/Tray,Intel,Efficiency-core Boost clock,3.9,GHz
262,Intel Core i5 7600T,Intel,Base clock,2.8,GHz
263,Intel Core i5 7600T,Intel,Boost clock,3.7,GHz
317,Intel Core i5 7600T,Intel,GPU base clock,350,MHz
318,Intel Core i5 7600T,Intel,GPU boost clock,1100,MHz
330,Intel Core i5 14400F,Intel,Base clock,2.5,GHz
331,Intel Core i5 14400F,Intel,Boost clock,4.7,GHz
332,Intel Core i5 14400F,Intel,Efficiency-core Base clock,1.8,GHz
333,Intel Core i5 14400F,Intel,Efficiency-core Boost clock,3.5,GHz
352,Intel Core i7 7700K,Intel,Base clock,4.2,GHz
353,Intel Core i7 7700K,Intel,Boost clock,4.5,GHz
408,Intel Core i7 7700K,Intel,GPU base clock,350,MHz
409,Intel Core i7 7700K,Intel,GPU boost clock,1150,MHz
419,AMD Ryzen Threadripper 1900X,AMD,Base clock,3.8,GHz
420,AMD Ryzen Threadripper 1900X,AMD,Boost clock,4,GHz
475,Intel Core i7 Extreme 6950X 3 GHz 10-Core LGA2...,Intel,Base clock,3,GHz
476,Intel Core i7 Extreme 6950X 3 GHz 10-Core LGA2...,Intel,Boost clock,3.5,GHz

Clock units:

      Count
Unit
MHz    2875
GHz    1260

In [10]:
# 1. Reshape the data: one row per CPU product
product_table = (
    cpu_products.pivot_table(
        index=["Object ID", "Object name", "Company"],
        columns="Specification",
        values="Value",
        aggfunc="first"
    )
    .reset_index()
)

product_table.columns.name = None

# 2. Convert selected specification fields to numeric values
numeric_fields = [
    "Cores", "Enabled CPU cores", "Threads",
    "L2 cache", "L3 cache",
    "Listed TDP", "Default TDP",
    "Record year", "Release year"
]

for col in numeric_fields:
    if col in product_table.columns:
        product_table[col] = pd.to_numeric(
            product_table[col], errors="coerce"
        )

# 3. Standardize core counts and TDP field names
if "Cores" in product_table.columns and "Enabled CPU cores" in product_table.columns:
    product_table["CPU cores"] = (
        product_table["Cores"].combine_first(
            product_table["Enabled CPU cores"]
        )
    )
elif "Cores" in product_table.columns:
    product_table["CPU cores"] = product_table["Cores"]
elif "Enabled CPU cores" in product_table.columns:
    product_table["CPU cores"] = product_table["Enabled CPU cores"]

if "Listed TDP" in product_table.columns and "Default TDP" in product_table.columns:
    product_table["TDP (W)"] = (
        product_table["Listed TDP"].combine_first(
            product_table["Default TDP"]
        )
    )
elif "Listed TDP" in product_table.columns:
    product_table["TDP (W)"] = product_table["Listed TDP"]
elif "Default TDP" in product_table.columns:
    product_table["TDP (W)"] = product_table["Default TDP"]

# 4. Standardize base and boost clocks to GHz
clock_long = cpu_products[
    cpu_products["Specification"].isin(["Base clock", "Boost clock"])
].copy()

clock_long["Value_num"] = pd.to_numeric(
    clock_long["Value"], errors="coerce"
)

clock_long["Unit"] = clock_long["Unit"].str.strip()

clock_long["Clock_GHz"] = np.where(
    clock_long["Unit"].eq("MHz"),
    clock_long["Value_num"] / 1000,
    np.where(
        clock_long["Unit"].eq("GHz"),
        clock_long["Value_num"],
        np.nan
    )
)

clock_wide = clock_long.pivot_table(
    index="Object ID",
    columns="Specification",
    values="Clock_GHz",
    aggfunc="first"
).reset_index()

clock_wide = clock_wide.rename(columns={
    "Base clock": "Base clock (GHz)",
    "Boost clock": "Boost clock (GHz)"
})

# Remove raw clock columns to avoid confusing them with normalized values
product_table = product_table.drop(
    columns=["Base clock", "Boost clock"],
    errors="ignore"
)

product_table = product_table.merge(
    clock_wide,
    on="Object ID",
    how="left",
    validate="one_to_one"
)

print("Product-level table shape:", product_table.shape)
print("Unique product IDs:", product_table["Object ID"].nunique())

display(
    product_table[
        [
            "Object name", "Company", "CPU cores", "Threads",
            "Base clock (GHz)", "Boost clock (GHz)", "TDP (W)"
        ]
    ].head(10)
)

Product-level table shape: (1621, 174)
Unique product IDs: 1621

,Object name,Company,CPU cores,Threads,Base clock (GHz),Boost clock (GHz),TDP (W)
0,AMD Ryzen 5 3600,AMD,6.0,12,NaN,NaN,NaN
1,AMD Ryzen 5 5600X,AMD,6.0,12,NaN,NaN,65.0
2,AMD Ryzen Threadripper 9980X,AMD,64.0,128,3.2,5.4,350.0
3,Intel Xeon E5 1650 V3 OEM/Tray 3.5 GHz 6-Core ...,Intel,6.0,12,3.5,3.8,140.0
4,Intel Xeon E3 1245 V5 OEM/Tray 3.5 GHz 4-Core ...,Intel,4.0,8,3.5,3.9,80.0
5,Intel Xeon E5-2660 v4,Intel,14.0,28,2.0,3.2,105.0
6,Intel Core i5 6400T OEM/Tray,Intel,4.0,4,2.2,2.8,35.0
7,Intel Core i9 13900T OEM/Tray,Intel,24.0,32,1.1,5.3,35.0
8,Intel Core i5 7600T,Intel,4.0,4,2.8,3.7,35.0
9,Intel Core i5 14400F,Intel,10.0,16,2.5,4.7,65.0

In [11]:
company_summary = (
    product_table.groupby("Company")
    .agg(
        Products=("Object ID", "nunique"),
        Products_with_core_data=("CPU cores", "count"),
        Products_with_base_clock=("Base clock (GHz)", "count"),
        Products_with_boost_clock=("Boost clock (GHz)", "count"),
        Products_with_TDP=("TDP (W)", "count"),
        Median_base_clock_GHz=("Base clock (GHz)", "median"),
        Median_boost_clock_GHz=("Boost clock (GHz)", "median"),
        Median_TDP_W=("TDP (W)", "median")
    )
    .reset_index()
)

display(company_summary.round(2))

,Company,Products,Products_with_core_data,Products_with_base_clock,Products_with_boost_clock,Products_with_TDP,Median_base_clock_GHz,Median_boost_clock_GHz,Median_TDP_W
0,AMD,383,383,381,356,378,3.25,4.1,65.0
1,Intel,1238,1238,1225,982,1228,2.60,3.7,65.0

In [12]:
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

product_table.to_csv(
    PROCESSED_DIR / "cpu_product_analysis.csv",
    index=False
)

company_summary.to_csv(
    REPORT_DIR / "cpu_company_summary.csv",
    index=False
)

print("Saved CPU product table:", len(product_table), "products")
print("Output folder:", PROCESSED_DIR)

Saved CPU product table: 1621 products
Output folder: C:\Users\udits\Documents\Chip-Product-Analysis\data\processed

In [13]:
# Find clock and power-related specification names in the source data
mask = df["Specification"].str.contains(
    r"clock|frequency|tdp|thermal design power",
    case=False,
    na=False
)

display(
    df.loc[mask, "Specification"]
      .value_counts()
      .to_frame("Record_Count")
)

                                                    Record_Count
Specification
Listed clock                                               10627
Base clock                                                  6080
Boost clock                                                 4931
Listed board TDP                                            3432
Effective memory clock                                      2780
Configured CPU clock                                        2085
Listed TDP                                                  1904
GPU boost clock                                              607
GPU base clock                                               570
CPU clock — frequency                                         86
CPU clock — frequency 2                                       84
Efficiency-core Base clock                                    56
Efficiency-core Boost clock                                   56
CPU clock — frequency 3                                       25
CPU clock — frequency 4                                       10
CPU clock — frequency 5                                        6
GPU base clock — Graphics / Integrated graphics...             5
GPU boost clock — Graphics / Integrated graphic...             5
GPU base clock — Graphics / Discrete graphics (...             5
GPU boost clock — Graphics / Discrete graphics ...             5
CPU peak frequency                                             5
CPU clock — frequency 6                                        4
CPU clock                                                      3
CPU clock — frequency 7                                        2
Peak CPU frequency                                             2
Default TDP                                                    1
Clock options                                                  1
CPU clocks                                                     1
Configured accelerator TDP                                     1
GPU clock                                                      1
Cortex-X1 clock                                                1
Reported GPU frequency range                                   1

In [14]:
check_cols = [
    "CPU cores",
    "Threads",
    "Base clock (GHz)",
    "Boost clock (GHz)",
    "TDP (W)"
]

for col in check_cols:
    if col in product_table.columns:
        missing_count = product_table[col].isna().sum()
        print(
            f"{col}: {missing_count} missing "
            f"({missing_count / len(product_table) * 100:.1f}%)"
        )

CPU cores: 0 missing (0.0%)
Threads: 0 missing (0.0%)
Base clock (GHz): 15 missing (0.9%)
Boost clock (GHz): 283 missing (17.5%)
TDP (W): 15 missing (0.9%)

In [15]:
# Choose products whose normalized clock values are missing
examples = product_table.loc[
    product_table["Base clock (GHz)"].isna(),
    ["Object ID", "Object name", "Company"]
].head(5)

display(examples)

# Show their clock-related records in the original dataset
clock_pattern = r"clock|frequency"

for object_id in examples["Object ID"]:
    print("\n" + "=" * 80)

    source_rows = df[
        (df["Object ID"] == object_id)
        & df["Specification"].str.contains(
            clock_pattern, case=False, na=False
        )
    ]

    display(
        source_rows[
            ["Object name", "Specification", "Value", "Unit"]
        ]
    )

               Object ID        Object name Company
0       amd-ryzen-5-3600   AMD Ryzen 5 3600     AMD
1      amd-ryzen-5-5600x  AMD Ryzen 5 5600X     AMD
705  cw-1df11c2fdb86f7d0       Core i5-8550   Intel
735  cw-246b8df1dc4ff989      Core i3-6320T   Intel
756  cw-2948d75756a01382       Core i5-8650   Intel

================================================================================

Empty DataFrame
Columns: [Object name, Specification, Value, Unit]
Index: []

================================================================================

Empty DataFrame
Columns: [Object name, Specification, Value, Unit]
Index: []

================================================================================

Empty DataFrame
Columns: [Object name, Specification, Value, Unit]
Index: []

================================================================================

          Object name    Specification Value Unit
165685  Core i3-6320T   GPU base clock   350  MHz
165686  Core i3-6320T  GPU boost clock   950  MHz

================================================================================

Empty DataFrame
Columns: [Object name, Specification, Value, Unit]
Index: []

In [16]:
comparison = (
    product_table.groupby("Company")
    .agg(
        Products=("Object ID", "nunique"),
        Core_data_available=("CPU cores", "count"),
        Threads_available=("Threads", "count"),
        Base_clock_available=("Base clock (GHz)", "count"),
        Boost_clock_available=("Boost clock (GHz)", "count"),
        TDP_available=("TDP (W)", "count")
    )
    .reset_index()
)

for metric in [
    "Core_data_available",
    "Threads_available",
    "Base_clock_available",
    "Boost_clock_available",
    "TDP_available"
]:
    comparison[metric + "_pct"] = (
        comparison[metric] / comparison["Products"] * 100
    ).round(1)

display(comparison)

,Company,Products,Core_data_available,Threads_available,Base_clock_available,Boost_clock_available,TDP_available,Core_data_available_pct,Threads_available_pct,Base_clock_available_pct,Boost_clock_available_pct,TDP_available_pct
0,AMD,383,383,383,381,356,378,100.0,100.0,99.5,93.0,98.7
1,Intel,1238,1238,1238,1225,982,1228,100.0,100.0,98.9,79.3,99.2

In [17]:
REPORT_DIR.mkdir(parents=True, exist_ok=True)

comparison.to_csv(
    REPORT_DIR / "cpu_specification_completeness_by_company.csv",
    index=False
)

print("Validation report saved successfully.")

Validation report saved successfully.

In [18]:
%pip install "psycopg[binary]" sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Collecting psycopg[binary]
  Downloading psycopg-3.3.6-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from psycopg[binary]) (2026.2)
Collecting psycopg-binary==3.3.6 (from psycopg[binary])
  Downloading psycopg_binary-3.3.6-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Downloading psycopg-3.3.6-py3-none-any.whl (215 kB)
Downloading psycopg_binary-3.3.6-cp314-cp314-win_amd64.whl (3.8 MB)
   ---------------------------------------- 0.0/3.8 MB ? eta -:--:--
   ---------------------- ----------------- 2.1/3.8 MB 11.4 MB/s eta 0:00:01
   ---------------------------------------- 3.8/3.8 MB 10.8 MB/s  0:00:00
Installing collected packages: psycopg-binary, psycopg

   ---------------------------------------- 0/2 [psycopg-binary]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   -------------------- ------------------- 1/2 [psycopg]
   ---------------------------------------- 2/2 [psycopg]

Successfully installed psycopg-3.3.6 psycopg-binary-3.3.6
Note: you may need to restart the kernel to use updated packages.

In [19]:
import psycopg
import sqlalchemy

print("Psycopg version:", psycopg.__version__)
print("SQLAlchemy version:", sqlalchemy.__version__)
print("Python PostgreSQL connector is ready!")

ModuleNotFoundError: No module named 'psycopg'

In [20]:
%pip install "psycopg[binary]" sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in C:\ProgramData\anaconda3\Lib\site-packages (2.0.51)
Requirement already satisfied: psycopg[binary] in C:\Users\udits\AppData\Roaming\Python\Python314\site-packages (3.3.6)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from psycopg[binary]) (2026.2)
Requirement already satisfied: psycopg-binary==3.3.6 in C:\Users\udits\AppData\Roaming\Python\Python314\site-packages (from psycopg[binary]) (3.3.6)
Requirement already satisfied: greenlet>=1 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\ProgramData\anaconda3\Lib\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

In [21]:
import sys
print(sys.executable)
print(sys.version)
print("\nPython package search paths:")
print("\n".join(sys.path))

C:\ProgramData\anaconda3\python.exe
3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]

Python package search paths:
C:\ProgramData\anaconda3\python314.zip
C:\ProgramData\anaconda3\DLLs
C:\ProgramData\anaconda3\Lib
C:\ProgramData\anaconda3

C:\ProgramData\anaconda3\Lib\site-packages
C:\ProgramData\anaconda3\Lib\site-packages\win32
C:\ProgramData\anaconda3\Lib\site-packages\win32\lib
C:\ProgramData\anaconda3\Lib\site-packages\pythonwin

In [22]:
import sys
!{sys.executable} -m pip install --user "psycopg[binary]"

Requirement already satisfied: psycopg[binary] in C:\Users\udits\AppData\Roaming\Python\Python314\site-packages (3.3.6)
Requirement already satisfied: tzdata in C:\ProgramData\anaconda3\Lib\site-packages (from psycopg[binary]) (2026.2)
Requirement already satisfied: psycopg-binary==3.3.6 in C:\Users\udits\AppData\Roaming\Python\Python314\site-packages (from psycopg[binary]) (3.3.6)

In [23]:
import psycopg
import sqlalchemy

print("Psycopg version:", psycopg.__version__)
print("SQLAlchemy version:", sqlalchemy.__version__)
print("Success — both packages imported!")

ModuleNotFoundError: No module named 'psycopg'

In [24]:
import sys
import site
import os

print("Python executable:", sys.executable)
print("Python version:", sys.version)
print("User site-packages:", site.getusersitepackages())
print("User site enabled:", site.ENABLE_USER_SITE)
print("User site on Python path:", site.getusersitepackages() in sys.path)
print("PYTHONNOUSERSITE:", os.environ.get("PYTHONNOUSERSITE"))

Python executable: C:\ProgramData\anaconda3\python.exe
Python version: 3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]
User site-packages: C:\Users\udits\AppData\Roaming\Python\Python314\site-packages
User site enabled: True
User site on Python path: False
PYTHONNOUSERSITE: None

In [25]:
import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip", "install",
    "--target", sys.prefix + r"\Lib\site-packages",
    "psycopg[binary]"
])

CalledProcessError: Command '['C:\\ProgramData\\anaconda3\\python.exe', '-m', 'pip', 'install', '--target', 'C:\\ProgramData\\anaconda3\\Lib\\site-packages', 'psycopg[binary]']' returned non-zero exit status 2.

In [26]:
import sys
import site
import os

print("Python executable:", sys.executable)
print("Python version:", sys.version)
print("User site-packages:", site.getusersitepackages())
print("User site enabled:", site.ENABLE_USER_SITE)
print("User site on Python path:",
      site.getusersitepackages() in sys.path)
print("PYTHONNOUSERSITE:", os.environ.get("PYTHONNOUSERSITE"))

Python executable: C:\ProgramData\anaconda3\python.exe
Python version: 3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]
User site-packages: C:\Users\udits\AppData\Roaming\Python\Python314\site-packages
User site enabled: True
User site on Python path: False
PYTHONNOUSERSITE: None

In [27]:
import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip",
    "install", "--user", "--upgrade", "psycopg[binary]"
])

0

In [1]:
import psycopg
print("Psycopg version:", psycopg.__version__)

Psycopg version: 3.3.6

In [2]:
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL
from getpass import getpass

# Enter your PostgreSQL login details
pg_user = input("PostgreSQL username [postgres]: ").strip() or "postgres"
pg_password = getpass("PostgreSQL password: ")

# Create the connection
connection_url = URL.create(
    drivername="postgresql+psycopg",
    username=pg_user,
    password=pg_password,
    host="localhost",
    port=5432,
    database="semiconductor_analysis"
)

engine = create_engine(connection_url)

# Test the connection
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT version();")
    )
    print("Connected successfully!")
    print(result.scalar())

PostgreSQL username [postgres]:  612001
PostgreSQL password:  ········

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "612001"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "612001"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "612001"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [4]:
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL
from getpass import getpass

# Enter your PostgreSQL login details
pg_user = input("PostgreSQL username [postgres]: ").strip() or "postgres"
pg_password = getpass("PostgreSQL password: ")

# Create the connection
connection_url = URL.create(
    drivername="postgresql+psycopg",
    username=pg_user,
    password=pg_password,
    host="localhost",
    port=5432,
    database="semiconductor_analysis"
)

engine = create_engine(connection_url)

# Test the connection
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT version();")
    )
    print("Connected successfully!")
    print(result.scalar())

PostgreSQL username [postgres]:  postgres
PostgreSQL password:  ········

Connected successfully!
PostgreSQL 18.6 on x86_64-windows, compiled by msvc-19.44.35229, 64-bit

In [5]:
from pathlib import Path
import pandas as pd
from sqlalchemy import text

PROJECT_DIR = Path.home() / "Documents" / "Chip-Product-Analysis"

csv_path = PROJECT_DIR / "data" / "processed" / "cpu_product_analysis.csv"

# Check that the file exists
print("File exists:", csv_path.exists())
print("CSV path:", csv_path)

File exists: True
CSV path: C:\Users\udits\Documents\Chip-Product-Analysis\data\processed\cpu_product_analysis.csv

In [1]:
# Read the processed CPU product table
cpu_df = pd.read_csv(csv_path)

print("Rows:", len(cpu_df))
print("Columns:", len(cpu_df.columns))

# Load into PostgreSQL
cpu_df.to_sql(
    name="cpu_products",
    con=engine,
    schema="public",
    if_exists="replace",
    index=False,
    chunksize=500,
    method="multi"
)

print("CPU product data loaded successfully!")

NameError: name 'pd' is not defined

In [2]:
with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM public.cpu_products")
    )
    print("Rows in PostgreSQL:", result.scalar())

NameError: name 'engine' is not defined

In [3]:
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL
from getpass import getpass

# Project folder and CSV path
PROJECT_DIR = Path.home() / "Documents" / "Chip-Product-Analysis"
csv_path = PROJECT_DIR / "data" / "processed" / "cpu_product_analysis.csv"

# Check the file
print("CSV exists:", csv_path.exists())
print("CSV path:", csv_path)

# Connect to PostgreSQL
pg_password = getpass("Enter your PostgreSQL password: ")

connection_url = URL.create(
    "postgresql+psycopg",
    username="postgres",
    password=pg_password,
    host="localhost",
    port=5432,
    database="semiconductor_analysis"
)

engine = create_engine(connection_url)

# Test the connection
with engine.connect() as connection:
    print("PostgreSQL connection successful!")

CSV exists: True
CSV path: C:\Users\udits\Documents\Chip-Product-Analysis\data\processed\cpu_product_analysis.csv

Enter your PostgreSQL password:  ········

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [4]:
from getpass import getpass
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

password = getpass("Enter the password you just set: ")

url = URL.create(
    "postgresql+psycopg",
    username="postgres",
    password=password,
    host="localhost",
    port=5432,
    database="semiconductor_analysis"
)

test_engine = create_engine(url)

with test_engine.connect() as conn:
    print(conn.execute(text(
        "SELECT current_user, current_database(), inet_server_port()"
    )).fetchone())

Enter the password you just set:  ········

OperationalError: (psycopg.OperationalError) connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
Multiple connection attempts failed. All failures were:
- host: 'localhost', port: 5432, hostaddr: '::1': connection failed: connection to server at "::1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
- host: 'localhost', port: 5432, hostaddr: '127.0.0.1': connection failed: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [5]:
from getpass import getpass
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

password = getpass("PostgreSQL password: ")

url = URL.create(
    "postgresql+psycopg",
    username="postgres",
    password=password,
    host="::1",
    port=5432,
    database="semiconductor_analysis"
)

test_engine = create_engine(url)

with test_engine.connect() as conn:
    print(conn.execute(
        text("SELECT current_user, current_database(), inet_server_port()")
    ).fetchone())

PostgreSQL password:  ········

('postgres', 'semiconductor_analysis', 5432)

In [6]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path.home() / "Documents" / "Chip-Product-Analysis"
csv_path = PROJECT_DIR / "data" / "processed" / "cpu_product_analysis.csv"

cpu_df = pd.read_csv(csv_path)

print("Rows:", len(cpu_df))
print("Columns:", len(cpu_df.columns))

Rows: 1621
Columns: 174

In [7]:
cpu_df.to_sql(
    name="cpu_products",
    con=test_engine,
    schema="public",
    if_exists="replace",
    index=False,
    chunksize=500
)

print("CPU product data loaded successfully!")

CPU product data loaded successfully!

In [8]:
from sqlalchemy import text

with test_engine.connect() as conn:
    count = conn.execute(
        text("SELECT COUNT(*) FROM public.cpu_products")
    ).scalar()

    print("Rows stored in PostgreSQL:", count)

Rows stored in PostgreSQL: 1621

In [9]:
from pathlib import Path
import pandas as pd

PROJECT_DIR = Path.home() / "Documents" / "Chip-Product-Analysis"
csv_path = PROJECT_DIR / "data" / "processed" / "cpu_product_analysis.csv"

cpu_df = pd.read_csv(csv_path)

print("File found:", csv_path.exists())
print("Rows:", len(cpu_df))
print("Columns:", len(cpu_df.columns))

display(cpu_df.head())

File found: True
Rows: 1621
Columns: 174

,Object ID,Object name,Company,Announcement date,Architecture,Boxed product ID,CPU clock — frequency,CPU clock — frequency 2,CPU clock — frequency 5,CPU family ID,...,Socket — package module 1,Stepping,Thermal junction maximum,Thermal junction minimum,Threads,Transistors,CPU cores,TDP (W),Base clock (GHz),Boost clock (GHz)
0,amd-ryzen-5-3600,AMD Ryzen 5 3600,AMD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12,NaN,6.0,NaN,NaN,NaN
1,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,AMD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12,NaN,6.0,65.0,NaN,NaN
2,bc-cpu-007a5a23-1e12-45b7-90d0-565b80876539,AMD Ryzen Threadripper 9980X,AMD,NaN,Zen 5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,128,NaN,64.0,350.0,3.2,5.4
3,bc-cpu-016d1180-e254-43da-ad22-67895ac633b6,Intel Xeon E5 1650 V3 OEM/Tray 3.5 GHz 6-Core ...,Intel,NaN,Haswell,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12,NaN,6.0,140.0,3.5,3.8
4,bc-cpu-019f71b2-930f-4546-8496-5947f1ef06cb,Intel Xeon E3 1245 V5 OEM/Tray 3.5 GHz 4-Core ...,Intel,NaN,Skylake,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8,NaN,4.0,80.0,3.5,3.9

In [10]:
from sqlalchemy import text

# Confirm the existing connection works
with test_engine.connect() as conn:
    print(
        conn.execute(
            text("SELECT current_database()")
        ).scalar()
    )

semiconductor_analysis

In [11]:
cpu_df.to_sql(
    name="cpu_products",
    con=test_engine,
    schema="public",
    if_exists="replace",
    index=False,
    chunksize=500
)

print("CPU product data imported successfully!")

CPU product data imported successfully!

In [12]:
with test_engine.connect() as conn:
    count = conn.execute(
        text("SELECT COUNT(*) FROM public.cpu_products")
    ).scalar()

    print("Rows in PostgreSQL:", count)

Rows in PostgreSQL: 1621

In [13]:
with test_engine.connect() as conn:
    sample = pd.read_sql(
        text("""
            SELECT *
            FROM public.cpu_products
            LIMIT 5
        """),
        conn
    )

display(sample)

,Object ID,Object name,Company,Announcement date,Architecture,Boxed product ID,CPU clock — frequency,CPU clock — frequency 2,CPU clock — frequency 5,CPU family ID,...,Socket — package module 1,Stepping,Thermal junction maximum,Thermal junction minimum,Threads,Transistors,CPU cores,TDP (W),Base clock (GHz),Boost clock (GHz)
0,amd-ryzen-5-3600,AMD Ryzen 5 3600,AMD,None,NaN,None,None,None,None,None,...,None,None,None,None,12,None,6.0,NaN,NaN,NaN
1,amd-ryzen-5-5600x,AMD Ryzen 5 5600X,AMD,None,NaN,None,None,None,None,None,...,None,None,None,None,12,None,6.0,65.0,NaN,NaN
2,bc-cpu-007a5a23-1e12-45b7-90d0-565b80876539,AMD Ryzen Threadripper 9980X,AMD,None,Zen 5,None,None,None,None,None,...,None,None,None,None,128,None,64.0,350.0,3.2,5.4
3,bc-cpu-016d1180-e254-43da-ad22-67895ac633b6,Intel Xeon E5 1650 V3 OEM/Tray 3.5 GHz 6-Core ...,Intel,None,Haswell,None,None,None,None,None,...,None,None,None,None,12,None,6.0,140.0,3.5,3.8
4,bc-cpu-019f71b2-930f-4546-8496-5947f1ef06cb,Intel Xeon E3 1245 V5 OEM/Tray 3.5 GHz 4-Core ...,Intel,None,Skylake,None,None,None,None,None,...,None,None,None,None,8,None,4.0,80.0,3.5,3.9

In [14]:
from sqlalchemy import text

with test_engine.connect() as conn:
    print(
        conn.execute(text("SELECT current_database()")).scalar()
    )

semiconductor_analysis

In [15]:
cpu_df.to_sql(
    name="cpu_products",
    con=test_engine,
    schema="public",
    if_exists="replace",
    index=False,
    chunksize=500
)

print("CPU product data imported successfully!")

CPU product data imported successfully!

In [16]:
with test_engine.connect() as conn:
    count = conn.execute(
        text("SELECT COUNT(*) FROM public.cpu_products")
    ).scalar()

    print("Rows in PostgreSQL:", count)

Rows in PostgreSQL: 1621

In [17]:
from sqlalchemy import text
import pandas as pd

query = text("""
    SELECT
        "Company",
        COUNT(*) AS total_products,
        ROUND(AVG("CPU cores"), 2) AS avg_cpu_cores,
        ROUND(AVG("Base clock (GHz)")::numeric, 2) AS avg_base_clock_ghz,
        ROUND(AVG("Boost clock (GHz)")::numeric, 2) AS avg_boost_clock_ghz,
        ROUND(AVG("TDP (W)")::numeric, 2) AS avg_tdp_watts
    FROM public.cpu_products
    WHERE "Company" IN ('AMD', 'Intel')
    GROUP BY "Company"
    ORDER BY "Company";
""")

with test_engine.connect() as conn:
    company_summary = pd.read_sql(query, conn)

display(company_summary)

DatabaseError: Execution failed on sql '
    SELECT
        "Company",
        COUNT(*) AS total_products,
        ROUND(AVG("CPU cores"), 2) AS avg_cpu_cores,
        ROUND(AVG("Base clock (GHz)")::numeric, 2) AS avg_base_clock_ghz,
        ROUND(AVG("Boost clock (GHz)")::numeric, 2) AS avg_boost_clock_ghz,
        ROUND(AVG("TDP (W)")::numeric, 2) AS avg_tdp_watts
    FROM public.cpu_products
    WHERE "Company" IN ('AMD', 'Intel')
    GROUP BY "Company"
    ORDER BY "Company";
': (psycopg.errors.UndefinedFunction) function round(double precision, integer) does not exist
LINE 5:         ROUND(AVG("CPU cores"), 2) AS avg_cpu_cores,
                ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[SQL:
    SELECT
        "Company",
        COUNT(*) AS total_products,
        ROUND(AVG("CPU cores"), 2) AS avg_cpu_cores,
        ROUND(AVG("Base clock (GHz)")::numeric, 2) AS avg_base_clock_ghz,
        ROUND(AVG("Boost clock (GHz)")::numeric, 2) AS avg_boost_clock_ghz,
        ROUND(AVG("TDP (W)")::numeric, 2) AS avg_tdp_watts
    FROM public.cpu_products
    WHERE "Company" IN ('AMD', 'Intel')
    GROUP BY "Company"
    ORDER BY "Company";
]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [18]:
from sqlalchemy import text
import pandas as pd

query = text("""
    SELECT
        "Company",
        COUNT(*) AS total_products,
        ROUND(AVG("CPU cores")::numeric, 2) AS avg_cpu_cores,
        ROUND(AVG("Base clock (GHz)")::numeric, 2) AS avg_base_clock_ghz,
        ROUND(AVG("Boost clock (GHz)")::numeric, 2) AS avg_boost_clock_ghz,
        ROUND(AVG("TDP (W)")::numeric, 2) AS avg_tdp_watts
    FROM public.cpu_products
    WHERE "Company" IN ('AMD', 'Intel')
    GROUP BY "Company"
    ORDER BY "Company";
""")

with test_engine.connect() as conn:
    company_summary = pd.read_sql(query, conn)

display(company_summary)

,Company,total_products,avg_cpu_cores,avg_base_clock_ghz,avg_boost_clock_ghz,avg_tdp_watts
0,AMD,383,12.50,3.13,4.15,105.13
1,Intel,1238,7.39,2.63,6.88,76.21

In [19]:
from sqlalchemy import text
import pandas as pd

query = text("""
    SELECT
        "Company",
        "Object name",
        "Boost clock (GHz)"
    FROM public.cpu_products
    WHERE "Boost clock (GHz)" IS NOT NULL
    ORDER BY "Boost clock (GHz)" DESC
    LIMIT 15;
""")

with test_engine.connect() as conn:
    highest_boost_clocks = pd.read_sql(query, conn)

display(highest_boost_clocks)

   Company            Object name  Boost clock (GHz)
0    Intel     Xeon Platinum 8175             3100.0
1    Intel  Intel Core i9 13900KS                6.0
2    Intel  Intel Core i9-14900KF                6.0
3    Intel  Intel Core i9 13900KF                5.8
4    Intel    Intel Core i9 14900                5.8
5    Intel   Intel Core i9 14900F                5.8
6    Intel   Intel Core i9 13900K                5.8
7    Intel  Intel Core i9-14900KS                5.7
8      AMD        AMD EPYC 4584PX                5.7
9      AMD      AMD Ryzen 9 9950X                5.7
10     AMD      AMD Ryzen 9 7950X                5.7
11     AMD    AMD Ryzen 9 7950X3D                5.7
12     AMD         AMD EPYC 4564P                5.7
13     AMD    AMD Ryzen 9 9950X3D                5.7
14     AMD    AMD Ryzen 9 7900X3D                5.6

In [20]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path.home() / "Documents" / "Chip-Product-Analysis"
source_path = PROJECT_DIR / "data" / "museum-fields-2026-10-04.csv"

source_df = pd.read_csv(source_path, dtype=str)

source_df.loc[
    source_df["Object name"].str.contains(
        "Xeon Platinum 8175", case=False, na=False
    )
    & source_df["Specification"].str.contains(
        "clock", case=False, na=False
    ),
    ["Object name", "Specification", "Value", "Unit",
     "Source-reported value", "Source-reported unit", "Source URL"]
]

,Object name,Specification,Value,Unit,Source-reported value,Source-reported unit,Source URL
175631,Xeon Platinum 8175,Base clock,2500,MHz,2500,MHz,https://chipswiki.org/index.php?title=Intel%2F...
175632,Xeon Platinum 8175,Boost clock,3100,GHz,3100,GHz,https://chipswiki.org/index.php?title=Intel%2F...
230212,Xeon Platinum 8175M,Base clock,2500,MHz,2500,MHz,https://chipswiki.org/index.php?title=Intel%2F...
230213,Xeon Platinum 8175M,Boost clock,3500,MHz,3500,MHz,https://chipswiki.org/index.php?title=Intel%2F...

In [1]:
import pandas as pd

# Make a separate copy for cleaned analysis
cpu_df_clean = cpu_df.copy()

# Identify the affected processor
bad_boost = (
    cpu_df_clean["Object name"].eq("Xeon Platinum 8175")
    & cpu_df_clean["Boost clock (GHz)"].gt(10)
)

print("Invalid boost-clock records found:", int(bad_boost.sum()))

# Exclude the unverified boost clock from analysis
cpu_df_clean.loc[bad_boost, "Boost clock (GHz)"] = float("nan")

print(
    cpu_df_clean.loc[
        cpu_df_clean["Object name"].eq("Xeon Platinum 8175"),
        ["Object name", "Base clock (GHz)", "Boost clock (GHz)"]
    ]
)

NameError: name 'cpu_df' is not defined

In [2]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_DIR = Path.home() / "Documents" / "Chip-Product-Analysis"

csv_path = (
    PROJECT_DIR
    / "data"
    / "processed"
    / "cpu_product_analysis.csv"
)

cpu_df = pd.read_csv(csv_path)

print("Rows:", len(cpu_df))
print("Columns:", len(cpu_df.columns))

Rows: 1621
Columns: 174

In [3]:
cpu_df_clean = cpu_df.copy()

bad_boost = (
    cpu_df_clean["Object name"].eq("Xeon Platinum 8175")
    & pd.to_numeric(
        cpu_df_clean["Boost clock (GHz)"],
        errors="coerce"
    ).gt(10)
)

print("Invalid boost-clock records found:", int(bad_boost.sum()))

cpu_df_clean.loc[bad_boost, "Boost clock (GHz)"] = np.nan

display(
    cpu_df_clean.loc[
        cpu_df_clean["Object name"].eq("Xeon Platinum 8175"),
        ["Object name", "Base clock (GHz)", "Boost clock (GHz)"]
    ]
)

Invalid boost-clock records found: 1

            Object name  Base clock (GHz)  Boost clock (GHz)
850  Xeon Platinum 8175               2.5                NaN

In [6]:
print("Cleaned data rows:", len(cpu_df_clean))
print(
    "Missing boost clock for Xeon Platinum 8175:",
    cpu_df_clean.loc[
        cpu_df_clean["Object name"].eq("Xeon Platinum 8175"),
        "Boost clock (GHz)"
    ].isna().all()
)

Cleaned data rows: 1621
Missing boost clock for Xeon Platinum 8175: True

In [7]:
cpu_df_clean.to_sql(
    name="cpu_products_clean",
    con=test_engine,
    schema="public",
    if_exists="replace",
    index=False,
    chunksize=500
)

print("Cleaned CPU data saved to PostgreSQL!")

NameError: name 'test_engine' is not defined

In [8]:
from getpass import getpass
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL

pg_password = getpass("Enter your PostgreSQL password: ")

connection_url = URL.create(
    "postgresql+psycopg",
    username="postgres",
    password=pg_password,
    host="::1",
    port=5432,
    database="semiconductor_analysis"
)

test_engine = create_engine(connection_url)

with test_engine.connect() as conn:
    print(
        "Connected to:",
        conn.execute(text("SELECT current_database()")).scalar()
    )

Enter your PostgreSQL password:  ········

Connected to: semiconductor_analysis

In [9]:
cpu_df_clean.to_sql(
    name="cpu_products_clean",
    con=test_engine,
    schema="public",
    if_exists="replace",
    index=False,
    chunksize=500
)

print("Cleaned CPU data saved to PostgreSQL!")

Cleaned CPU data saved to PostgreSQL!

In [10]:
with test_engine.connect() as conn:
    result = conn.execute(text("""
        SELECT
            COUNT(*) AS total_products,
            COUNT(*) FILTER (
                WHERE "Object name" = 'Xeon Platinum 8175'
                  AND "Boost clock (GHz)" IS NULL
            ) AS corrected_records
        FROM public.cpu_products_clean;
    """))

    print(result.fetchone())

(1621, 1)

In [11]:
SELECT
    "Company",
    COUNT(*) AS total_products,
    ROUND(AVG("CPU cores")::numeric, 2) AS avg_cpu_cores,
    ROUND(AVG("Base clock (GHz)")::numeric, 2) AS avg_base_clock_ghz,
    ROUND(AVG("Boost clock (GHz)")::numeric, 2) AS avg_boost_clock_ghz,
    ROUND(AVG("TDP (W)")::numeric, 2) AS avg_tdp_watts
FROM public.cpu_products_clean
WHERE "Company" IN ('AMD', 'Intel')
GROUP BY "Company"
ORDER BY "Company";

IndentationError: unexpected indent (2059510642.py, line 2)